[local]
localhost

[mongodb]
mongodb.awspractice.sbs

[mysql]
mysql.awspractice.sbs

[redis]
redis.awspractice.sbs

[rabbitmq]
rabbitmq.awspractice.sbs

[catalogue]
catalogue.awspractice.sbs

[cart]
cart.awspractice.sbs

[user]
user.awspractice.sbs

[payment]
payment.awspractice.sbs

[shipping]
shipping.awspractice.sbs

[frontend]
frontend.awspractice.sbs

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

